import { Link, router } from 'expo-router';
import { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { Button, Field, Screen } from '@/components/ui';
import { colors } from '@/constants/design';
import { friendlyError } from '@/lib/errors';
import { authRepository } from '@/repositories/auth-repository';
export default function Login() { const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [visible, setVisible] = useState(false); const [loading, setLoading] = useState(false);
  const submit = async () => { if (!email || !password) return Alert.alert('Enter your details', 'Your email and password are both required.'); setLoading(true); try { await authRepository.login(email, password); router.replace('/(app)/(tabs)'); } catch (error) { Alert.alert('Could not sign in', friendlyError(error, 'Please check your details and try again.')); } finally { setLoading(false); } };
  return <Screen style={styles.screen}><View style={styles.brand}><View style={styles.mark}><Text style={styles.markText}>G</Text></View><Text style={styles.title}>Welcome back</Text><Text style={styles.sub}>Your build. Every expense, in one calm place.</Text></View><View style={styles.form}><Field label="Email address" value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" autoComplete="email" placeholder="you@example.com" /><Field label="Password" value={password} onChangeText={setPassword} secureTextEntry={!visible} autoComplete="password" placeholder="Your password" right={<Pressable accessibilityRole="button" accessibilityLabel={visible ? 'Hide password' : 'Show password'} onPress={() => setVisible((current) => !current)} style={styles.eye}><Text style={styles.eyeText}>{visible ? 'Hide' : 'Show'}</Text></Pressable>} /><Link href="/(auth)/forgot-password" style={styles.link}>Forgot password?</Link><Button loading={loading} onPress={submit}>Sign in</Button></View><Text style={styles.bottom}>New to GharKhata? <Link href="/(auth)/signup" style={styles.link}>Create an account</Link></Text></Screen>; }
const styles = StyleSheet.create({ screen: { justifyContent: 'center', gap: 40, paddingHorizontal: 25 }, brand: { gap: 9 }, mark: { backgroundColor: colors.forest, width: 50, height: 50, borderRadius: 16, alignItems: 'center', justifyContent: 'center', marginBottom: 8 }, markText: { color: 'white', fontSize: 28, fontWeight: '900' }, title: { fontSize: 34, fontWeight: '900', color: colors.ink, letterSpacing: -.8 }, sub: { color: colors.muted, fontSize: 16, lineHeight: 23, maxWidth: 280 }, form: { gap: 17 }, link: { color: colors.forest, fontWeight: '800', alignSelf: 'flex-start' }, bottom: { color: colors.muted, textAlign: 'center', fontSize: 14 }, eye: { minHeight: 48, justifyContent: 'center', paddingHorizontal: 14 }, eyeText: { color: colors.forest, fontWeight: '900', fontSize: 13 } });
