import { Link, router } from 'expo-router';
import { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { Button, Field, Screen } from '@/components/ui';
import { colors } from '@/constants/design';
import { friendlyError } from '@/lib/errors';
import { authRepository } from '@/repositories/auth-repository';
export default function Signup() { const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [visible, setVisible] = useState(false); const [loading, setLoading] = useState(false);
  const submit = async () => { if (!name || !email || password.length < 6) return Alert.alert('Check your details', 'Add your name, a valid email, and a password with at least 6 characters.'); setLoading(true); try { await authRepository.signup(name, email, password); router.replace('/(app)/project-form'); } catch (error) { Alert.alert('Could not create account', friendlyError(error, 'Please try again in a moment.')); } finally { setLoading(false); } };
  return <Screen style={styles.screen}><View style={styles.brand}><Text style={styles.eyebrow}>GHARKHATA</Text><Text style={styles.title}>Build with clarity.</Text><Text style={styles.sub}>Start with your project, then add expenses as they happen.</Text></View><View style={styles.form}><Field label="Your name" value={name} onChangeText={setName} autoComplete="name" placeholder="How should we call you?" /><Field label="Email address" value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" autoComplete="email" placeholder="you@example.com" /><Field label="Password" value={password} onChangeText={setPassword} secureTextEntry={!visible} autoComplete="new-password" placeholder="At least 6 characters" right={<Pressable accessibilityRole="button" accessibilityLabel={visible ? 'Hide password' : 'Show password'} onPress={() => setVisible((current) => !current)} style={styles.eye}><Text style={styles.eyeText}>{visible ? 'Hide' : 'Show'}</Text></Pressable>} /><Button loading={loading} onPress={submit}>Create account</Button></View><Text style={styles.bottom}>Already have an account? <Link href="/(auth)/login" style={styles.link}>Sign in</Link></Text></Screen>; }
const styles = StyleSheet.create({ screen: { justifyContent: 'center', gap: 36, paddingHorizontal: 25 }, brand: { gap: 8 }, eyebrow: { color: colors.forest, fontWeight: '900', letterSpacing: 1.8, fontSize: 12 }, title: { fontSize: 34, fontWeight: '900', color: colors.ink, letterSpacing: -.8 }, sub: { color: colors.muted, fontSize: 16, lineHeight: 23 }, form: { gap: 16 }, bottom: { color: colors.muted, textAlign: 'center', fontSize: 14 }, link: { color: colors.forest, fontWeight: '800' }, eye: { minHeight: 48, justifyContent: 'center', paddingHorizontal: 14 }, eyeText: { color: colors.forest, fontWeight: '900', fontSize: 13 } });
