import { useEffect, useState } from 'react';
import { Alert, StyleSheet, Text, View } from 'react-native';
import { Button, Card, EmptyState, Field, Header, Pill, Screen, Selector } from '@/components/ui';
import { colors } from '@/constants/design';
import { friendlyError } from '@/lib/errors';
import { useProfiles, useProjectMembers, useProjects } from '@/hooks/use-project-data';
import { inviteRepository } from '@/repositories/invite-repository';
import { useApp } from '@/providers/app-provider';
import type { ProjectInvite, ProjectRole } from '@/types/domain';

const roles = [{ id: 'admin', name: 'Admin' }, { id: 'editor', name: 'Editor' }, { id: 'viewer', name: 'Viewer' }];

export default function Members() {
  const { user, profile } = useApp(); const projects = useProjects(user?.uid); const project = projects.find((item) => item.id === profile?.selectedProjectId) ?? projects[0];
  const members = useProjectMembers(project?.id); const profiles = useProfiles(members.map((member) => member.userId));
  const [email, setEmail] = useState(''); const [role, setRole] = useState<ProjectRole>('editor'); const [saving, setSaving] = useState(false); const [removingId, setRemovingId] = useState<string>(); const [updatingId, setUpdatingId] = useState<string>(); const [invites, setInvites] = useState<ProjectInvite[]>([]);
  const canManage = Boolean(project && project.status === 'active' && user && project.role === 'admin');
  useEffect(() => project && canManage ? inviteRepository.watchForProject(project.id, setInvites) : undefined, [project?.id, canManage]);
  const invite = async () => { if (!project || !user || !email.trim()) return; setSaving(true); try { await inviteRepository.invite(user.uid, project, email, role); setEmail(''); Alert.alert('Invitation saved', 'They can accept it from their Invitations screen.'); } catch (error) { Alert.alert('Could not invite collaborator', friendlyError(error, 'Please check the email and try again.')); } finally { setSaving(false); } };
  const updateRole = (memberId: string) => { if (!project) return; const member = members.find((item) => item.userId === memberId); if (!member) return; const nextRole: ProjectRole = member.role === 'viewer' ? 'editor' : member.role === 'editor' ? 'admin' : 'viewer'; Alert.alert('Change role?', `${profiles[memberId]?.displayName || 'This collaborator'} will become ${nextRole}.`, [{ text: 'Cancel', style: 'cancel' }, { text: 'Change role', onPress: async () => { setUpdatingId(memberId); try { await inviteRepository.updateMemberRole(project.id, memberId, nextRole); } catch (error) { Alert.alert('Could not update role', friendlyError(error, 'Please try again.')); } finally { setUpdatingId(undefined); } } }]); };
  const remove = (memberId: string) => { if (!project) return; Alert.alert('Remove collaborator?', 'They will no longer be able to access this project.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Remove', style: 'destructive', onPress: async () => { setRemovingId(memberId); try { await inviteRepository.removeMember(project.id, memberId, invites.filter((invite) => invite.acceptedBy === memberId).map((invite) => invite.id)); Alert.alert('Member removed', 'Their access to this project has been removed.'); } catch (error) { Alert.alert('Could not remove member', friendlyError(error, 'Please try again.')); } finally { setRemovingId(undefined); } } }]); };
  if (!project) return <Screen><Header title="Project members" /><EmptyState title="Create a project first" body="You can invite collaborators after creating a project." /></Screen>;
  if (project.status === 'archived') return <Screen><Header title="Project members" subtitle="Archived project · view only." /><EmptyState title="Project archived" body="Reactivate the project from Projects before changing members or invitations." /></Screen>;
  if (!canManage) return <Screen><Header title="Project members" /><EmptyState title="Admin access required" body="Only project owners and admins can invite or remove members." /></Screen>;
  const pending = invites.filter((invite) => invite.status === 'pending');
  return <Screen><Header title="Project members" subtitle={`Invite people to ${project.name}.`} /><Card style={styles.invite}><Field label="Collaborator email" value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="person@example.com" /><Selector label="Role" value={role} options={roles} onChange={(value) => setRole(value as ProjectRole)} /><Button loading={saving} onPress={invite}>Invite collaborator</Button></Card><Text style={styles.help}>Sending the same email again refreshes its invitation and role.</Text><Text style={styles.section}>Team ({members.length})</Text><Card style={styles.list}>{members.map((member) => { const memberName = profiles[member.userId]?.displayName || (member.userId === user?.uid ? 'You' : 'Collaborator'); return <View key={member.id} style={styles.row}><View style={styles.member}><Text style={styles.memberName}>{memberName}</Text><Text numberOfLines={1} style={styles.memberId}>{member.userId}</Text></View><View style={styles.actions}><Pill tone={member.role === 'viewer' ? 'soft' : 'green'}>{member.userId === project.ownerId ? 'Owner' : member.role}</Pill>{member.userId !== project.ownerId ? <View style={styles.memberButtons}><Button loading={updatingId === member.userId} variant="secondary" style={styles.memberButton} onPress={() => updateRole(member.userId)}>Change role</Button><Button loading={removingId === member.userId} variant="ghost" style={styles.memberButton} onPress={() => remove(member.userId)}>Remove</Button></View> : null}</View></View>; })}</Card><Text style={styles.section}>Invitations ({pending.length} pending)</Text>{pending.length ? <Card style={styles.list}>{pending.map((invite) => <View key={invite.id} style={styles.row}><View style={styles.member}><Text style={styles.memberName}>{invite.invitedEmail}</Text><Text style={styles.memberId}>{invite.role} · pending</Text></View><Pill tone="amber">pending</Pill></View>)}</Card> : <Text style={styles.help}>No pending invitations.</Text>}</Screen>;
}
const styles = StyleSheet.create({ invite: { gap: 14 }, help: { color: colors.muted, fontSize: 13, lineHeight: 18 }, section: { color: colors.ink, fontWeight: '900', fontSize: 18, marginTop: 2 }, list: { paddingVertical: 0 }, row: { minHeight: 76, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12, borderBottomColor: colors.line, borderBottomWidth: 1 }, member: { flex: 1 }, memberName: { color: colors.ink, fontWeight: '900' }, memberId: { color: colors.muted, fontSize: 11, marginTop: 3 }, actions: { alignItems: 'flex-end', gap: 5 }, memberButtons: { flexDirection: 'row', gap: 6 }, memberButton: { minHeight: 31, borderRadius: 10, paddingHorizontal: 9 } });
