import { router } from 'expo-router';
import { useState } from 'react';
import { Alert, StyleSheet, Text } from 'react-native';
import { Button, Field, Header, Screen } from '@/components/ui';
import { friendlyError } from '@/lib/errors';
import { today } from '@/lib/format';
import { masterRepository } from '@/repositories/master-repository';
import { profileRepository } from '@/repositories/profile-repository';
import { projectRepository } from '@/repositories/project-repository';
import { useApp } from '@/providers/app-provider';
export default function ProjectForm() { const { user, profile, currency } = useApp(); const [name, setName] = useState(''); const [budget, setBudget] = useState(''); const [location, setLocation] = useState(''); const [houseType, setHouseType] = useState(''); const [loading, setLoading] = useState(false); const save = async () => { if (!user || !name.trim()) return Alert.alert('Name your project', 'For example: My 25×45 G+2 House.'); setLoading(true); try { const actorName = profile?.displayName || user.displayName || 'Project owner'; const id = await projectRepository.create(user.uid, actorName, { name: name.trim(), description: '', houseType, location, totalBudget: Number(budget) || 0, currency, startDate: today(), status: 'active' }); await masterRepository.seed(user.uid, id, actorName); await profileRepository.selectProject(user.uid, id); router.replace('/(app)/(tabs)'); } catch (error) { Alert.alert('Could not save project', friendlyError(error, 'Please try again.')); } finally { setLoading(false); } }; return <Screen><Header title="Your project" subtitle="A few details to set the foundation." /><Field label="Project name" value={name} onChangeText={setName} placeholder="My 25×45 G+2 House" autoFocus /><Field label="Total budget (optional)" value={budget} onChangeText={setBudget} placeholder="0" keyboardType="decimal-pad" /><Field label="Location (optional)" value={location} onChangeText={setLocation} placeholder="Bengaluru, Karnataka" /><Field label="House type (optional)" value={houseType} onChangeText={setHouseType} placeholder="G+2 / Renovation / Villa" /><Text style={styles.note}>You can refine budgets and project details later.</Text><Button loading={loading} onPress={save}>Create project</Button><Button variant="ghost" onPress={() => router.back()}>Cancel</Button></Screen>; }
const styles = StyleSheet.create({ note: { color: '#68746D', fontSize: 13, marginTop: -5 } });
