import { router } from 'expo-router';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { AuditText, Button, Card, EmptyState, Header, Pill, Screen, SectionTitle } from '@/components/ui';
import { colors } from '@/constants/design';
import { formatCurrency } from '@/lib/format';
import { useProjects } from '@/hooks/use-project-data';
import { profileRepository } from '@/repositories/profile-repository';
import { projectRepository } from '@/repositories/project-repository';
import { useApp } from '@/providers/app-provider';
import type { ProjectAccess } from '@/types/domain';

export default function Projects() {
  const { user, profile, currency } = useApp(); const projects = useProjects(user?.uid); const active = projects.filter((project) => project.status === 'active'); const archived = projects.filter((project) => project.status === 'archived');
  const select = async (id: string) => { if (user) { await profileRepository.selectProject(user.uid, id); router.back(); } };
  const archive = (project: ProjectAccess) => Alert.alert(`Archive ${project.name}?`, 'It becomes read-only. Expenses, budgets and team data stay safe and can be reactivated later.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Archive', onPress: () => user && projectRepository.archive(user.uid, project.id) }]);
  const reactivate = (project: ProjectAccess) => Alert.alert(`Reactivate ${project.name}?`, 'It will become editable for its team again.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Reactivate', onPress: () => user && projectRepository.reactivate(user.uid, project.id) }]);
  const remove = (project: ProjectAccess) => Alert.alert(`Delete ${project.name}?`, 'This permanently deletes the project, its team links, expenses, budgets, and shared lists. This cannot be undone.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete project', style: 'destructive', onPress: async () => { if (!user) return; try { await projectRepository.delete(project.id); if (profile?.selectedProjectId === project.id) await profileRepository.selectProject(user.uid, ''); } catch { Alert.alert('Could not delete project', 'Please try again.'); } } }]);
  const renderProject = (project: ProjectAccess) => <Card key={project.id} style={{ ...styles.project, ...(project.status === 'archived' ? styles.archivedCard : {}) }}><Pressable onPress={() => select(project.id)}><View style={styles.projectTop}><View style={styles.flex}><Text style={styles.name}>{project.name}</Text><Text style={styles.details}>{project.location || project.houseType || 'Construction project'}</Text></View>{project.id === profile?.selectedProjectId ? <Pill tone={project.status === 'archived' ? 'amber' : 'green'}>{project.status === 'archived' ? 'Archived' : 'Active'}</Pill> : <Pill>{project.status}</Pill>}</View><Text style={styles.budget}>{project.totalBudget ? formatCurrency(project.totalBudget, currency) : 'No budget set'}</Text><Text style={styles.role}>{project.ownerId === user?.uid ? 'Owner' : project.role}</Text><AuditText createdBy={project.ownerId} updatedBy={project.updatedBy} />{project.status === 'archived' ? <Text style={styles.readOnly}>Archived · view only</Text> : null}</Pressable>{project.role === 'admin' ? <View style={styles.projectActions}>{project.status === 'active' ? <Pressable onPress={() => archive(project)}><Text style={styles.archive}>Archive project</Text></Pressable> : <Pressable onPress={() => reactivate(project)}><Text style={styles.reactivate}>Reactivate project</Text></Pressable>}{project.ownerId === user?.uid ? <Pressable onPress={() => remove(project)}><Text style={styles.delete}>Delete project</Text></Pressable> : null}</View> : null}</Card>;
  return <Screen><Header title="Projects" subtitle="Keep every build organized." />{active.length ? <><SectionTitle title={`Active projects (${active.length})`} /><View style={styles.list}>{active.map(renderProject)}</View></> : <EmptyState title="No active projects" body="Create a project or reactivate a completed one." />}{archived.length ? <><SectionTitle title={`Archived projects (${archived.length})`} /><Text style={styles.archiveInfo}>Archived projects remain available for reference but cannot be edited until reactivated.</Text><View style={styles.list}>{archived.map(renderProject)}</View></> : null}<Button onPress={() => router.push('/(app)/project-form')}>Create project</Button></Screen>;
}
const styles = StyleSheet.create({ list: { gap: 11 }, project: { gap: 15 }, archivedCard: { backgroundColor: '#FAFBF9' }, projectTop: { flexDirection: 'row', justifyContent: 'space-between', gap: 10 }, flex: { flex: 1 }, name: { color: colors.ink, fontSize: 17, fontWeight: '900' }, details: { color: colors.muted, fontSize: 13, marginTop: 4 }, budget: { color: colors.forest, fontWeight: '900', fontSize: 16 }, role: { color: colors.muted, fontSize: 12, fontWeight: '800', textTransform: 'capitalize' }, readOnly: { color: '#8A6F20', fontSize: 12, fontWeight: '800' }, projectActions: { flexDirection: 'row', justifyContent: 'space-between' }, archive: { color: colors.coral, fontWeight: '800', fontSize: 13 }, reactivate: { color: colors.forest, fontWeight: '800', fontSize: 13 }, delete: { color: colors.coral, fontWeight: '900', fontSize: 13 }, archiveInfo: { color: colors.muted, fontSize: 13, lineHeight: 18, marginTop: -10 } });
