import { router } from 'expo-router';
import { useMemo } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Button, Card, EmptyState, Header, Pill, Screen, SectionTitle } from '@/components/ui';
import { ProjectPicker } from '@/components/project-picker';
import { colors } from '@/constants/design';
import { budgetRows, expenseTotal } from '@/lib/analytics';
import { formatCurrency } from '@/lib/format';
import { useBudget, useExpenses, useMaster, useProjects } from '@/hooks/use-project-data';
import { useApp } from '@/providers/app-provider';
export default function BudgetScreen() { const { user, profile, currency } = useApp(); const projects = useProjects(user?.uid); const project = projects.find((item) => item.id === profile?.selectedProjectId) ?? projects[0]; const { items: expenses } = useExpenses(user?.uid, project?.id); const categories = useMaster(project?.id, 'categories'); const budget = useBudget(user?.uid, project?.id); if (!project) return <Screen><EmptyState title="Create a project first" body="Budgets belong to a construction project." action={<Button onPress={() => router.push('/(app)/project-form')}>Create project</Button>} /></Screen>; const total = budget?.totalBudget ?? project.totalBudget; const spent = expenseTotal(expenses); const rows = budgetRows(budget, expenses, categories); return <Screen><Header title="Budget" subtitle="Plan with confidence." right={<ProjectPicker projects={projects} />} />{total ? <Card style={styles.summary}><Text style={styles.label}>AVAILABLE TO SPEND</Text><Text style={styles.remaining}>{formatCurrency(Math.max(total - spent, 0), currency)}</Text><View style={styles.summaryLine}><Text style={styles.spent}>Spent {formatCurrency(spent, currency)}</Text><Text style={styles.spent}>of {formatCurrency(total, currency)}</Text></View><View style={styles.track}><View style={[styles.fill, { width: `${Math.min((spent / total) * 100, 100)}%` }]} /></View></Card> : <EmptyState icon="◔" title="Set your first budget" body="Add a total and optional category allocations, then compare planned vs actual spending." action={<Button onPress={() => router.push('/(app)/budget-form')}>Set budget</Button>} />}{total ? <><SectionTitle title="Category budgets" action={rows.length ? 'Budget vs actual' : undefined} />{rows.length ? <Card style={styles.rows}>{rows.map((row) => <View key={row.categoryId} style={styles.row}><View><Text style={styles.rowName}>{row.name}</Text><Text style={styles.rowSub}>{formatCurrency(row.actual, currency)} spent of {formatCurrency(row.budget, currency)}</Text></View><Pill tone={row.difference < 0 ? 'coral' : row.actual / row.budget > .8 ? 'amber' : 'green'}>{row.difference < 0 ? `${formatCurrency(-row.difference, currency)} over` : `${formatCurrency(row.difference, currency)} left`}</Pill></View>)}</Card> : <Card><Text style={styles.emptyText}>No category allocations yet. Add them to spot overruns early.</Text></Card>}<Button variant="secondary" onPress={() => router.push('/(app)/budget-form')}>Edit budget</Button></> : null}</Screen>; }
const styles = StyleSheet.create({ summary: { backgroundColor: colors.forest, borderColor: colors.forest, gap: 9 }, label: { color: '#BDE1CA', fontSize: 11, letterSpacing: .9, fontWeight: '900' }, remaining: { color: 'white', fontSize: 32, fontWeight: '900' }, summaryLine: { flexDirection: 'row', justifyContent: 'space-between' }, spent: { color: '#D5ECDE', fontSize: 12, fontWeight: '700' }, track: { height: 7, borderRadius: 4, backgroundColor: '#438B6B', overflow: 'hidden' }, fill: { height: '100%', backgroundColor: colors.lime }, rows: { gap: 16 }, row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 10 }, rowName: { color: colors.ink, fontWeight: '900', fontSize: 15 }, rowSub: { color: colors.muted, fontSize: 12, marginTop: 3 }, emptyText: { color: colors.muted, lineHeight: 20 } });
