import { router } from 'expo-router';
import { StyleSheet, Text, View } from 'react-native';
import { AuditText, Button, Card, EmptyState, Header, Pill, Screen, SectionTitle } from '@/components/ui';
import { ProjectPicker } from '@/components/project-picker';
import { colors } from '@/constants/design';
import { budgetRows, expenseTotal } from '@/lib/analytics';
import { formatCurrency } from '@/lib/format';
import { useBudget, useExpenses, useMaster, useProjects } from '@/hooks/use-project-data';
import { useApp } from '@/providers/app-provider';

export default function BudgetScreen() {
  const { user, profile, currency } = useApp(); const projects = useProjects(user?.uid); const project = projects.find((item) => item.id === profile?.selectedProjectId) ?? projects[0];
  const { items: expenses } = useExpenses(user?.uid, project?.id); const categories = useMaster(project?.id, 'categories'); const budget = useBudget(user?.uid, project?.id);
  if (!project) return <Screen><EmptyState title="Create a project first" body="Budgets belong to a construction project." action={<Button onPress={() => router.push('/(app)/project-form')}>Create project</Button>} /></Screen>;
  const total = budget?.totalBudget ?? project.totalBudget; const spent = expenseTotal(expenses); const overrun = Math.max(spent - total, 0); const isOverBudget = Boolean(total && overrun > 0); const rows = budgetRows(budget, expenses, categories);
  const canPlan = Boolean(project.status === 'active' && user && (project.ownerId === user.uid || project.memberRoles[user.uid] === 'admin'));
  const setBudget = () => router.push('/(app)/budget-form');
  return <Screen><Header title="Budget" subtitle={project.status === 'archived' ? 'Archived project · view only.' : 'Plan with confidence.'} right={<ProjectPicker projects={projects} />} />
    {total ? <><Card style={isOverBudget ? styles.overrunSummary : styles.summary}><Text style={styles.label}>{isOverBudget ? 'BUDGET EXCEEDED' : 'AVAILABLE TO SPEND'}</Text><Text style={styles.remaining}>{isOverBudget ? `${formatCurrency(overrun, currency)} over` : formatCurrency(Math.max(total - spent, 0), currency)}</Text><View style={styles.summaryLine}><Text style={styles.spent}>Spent {formatCurrency(spent, currency)}</Text><Text style={styles.spent}>of {formatCurrency(total, currency)}</Text></View><View style={styles.track}><View style={[styles.fill, isOverBudget && styles.overrunFill, { width: `${Math.min((spent / total) * 100, 100)}%` }]} /></View></Card>{isOverBudget ? <Card style={styles.warning}><Text style={styles.warningTitle}>Your project is over budget</Text><Text style={styles.warningText}>Spending is {formatCurrency(overrun, currency)} above the planned budget. Review upcoming expenses or revise the plan.</Text>{canPlan ? <Button variant="secondary" onPress={setBudget}>Review budget</Button> : null}</Card> : null}</> : <EmptyState icon="◔" title={project.status === 'archived' ? 'No budget recorded' : 'Set your first budget'} body={project.status === 'archived' ? 'This archived project has no budget and remains view-only.' : 'Add a total and optional category allocations, then compare planned vs actual spending.'} action={canPlan ? <Button onPress={setBudget}>Set budget</Button> : undefined} />}
    {budget ? <AuditText updatedByName={budget.updatedByName} /> : null}{total ? <><SectionTitle title="Category budgets" action={rows.length ? 'Budget vs actual' : undefined} />{rows.length ? <Card style={styles.rows}>{rows.map((row) => <View key={row.categoryId} style={styles.row}><View><Text style={styles.rowName}>{row.name}</Text><Text style={styles.rowSub}>{formatCurrency(row.actual, currency)} spent of {formatCurrency(row.budget, currency)}</Text></View><Pill tone={row.difference < 0 ? 'coral' : row.actual / row.budget > .8 ? 'amber' : 'green'}>{row.difference < 0 ? `${formatCurrency(-row.difference, currency)} over` : `${formatCurrency(row.difference, currency)} left`}</Pill></View>)}</Card> : <Card><Text style={styles.emptyText}>No category allocations yet. Add them to spot overruns early.</Text></Card>}{canPlan ? <Button variant="secondary" onPress={setBudget}>Edit budget</Button> : null}</> : null}
  </Screen>;
}
const styles = StyleSheet.create({ summary: { backgroundColor: colors.forest, borderColor: colors.forest, gap: 9 }, overrunSummary: { backgroundColor: colors.coral, borderColor: colors.coral, gap: 9 }, label: { color: '#FFF6F3', fontSize: 11, letterSpacing: .9, fontWeight: '900' }, remaining: { color: 'white', fontSize: 32, fontWeight: '900' }, summaryLine: { flexDirection: 'row', justifyContent: 'space-between' }, spent: { color: '#FFF6F3', fontSize: 12, fontWeight: '700' }, track: { height: 7, borderRadius: 4, backgroundColor: 'rgba(255,255,255,.34)', overflow: 'hidden' }, fill: { height: '100%', backgroundColor: colors.lime }, overrunFill: { backgroundColor: '#8B2E1F' }, warning: { backgroundColor: '#FFF0EB', borderColor: '#F5B6A8', gap: 8 }, warningTitle: { color: '#8B2E1F', fontSize: 16, fontWeight: '900' }, warningText: { color: colors.ink, lineHeight: 19, fontSize: 13 }, rows: { gap: 16 }, row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 10 }, rowName: { color: colors.ink, fontWeight: '900', fontSize: 15 }, rowSub: { color: colors.muted, fontSize: 12, marginTop: 3 }, emptyText: { color: colors.muted, lineHeight: 20 } });
