import { router } from 'expo-router';
import { StyleSheet, Text, View } from 'react-native';
import { Button, Card, EmptyState, Header, Pill, Screen, SectionTitle } from '@/components/ui';
import { ProjectPicker } from '@/components/project-picker';
import { colors } from '@/constants/design';
import { categoryTotals, expenseTotal, monthTotal } from '@/lib/analytics';
import { formatCurrency } from '@/lib/format';
import { useBudget, useExpenses, useMaster, useProjects } from '@/hooks/use-project-data';
import { useApp } from '@/providers/app-provider';

export default function Dashboard() {
  const { user, profile, currency } = useApp(); const projects = useProjects(user?.uid);
  const selected = projects.find((item) => item.id === profile?.selectedProjectId) ?? projects[0];
  const { items: expenses } = useExpenses(user?.uid, selected?.id); const budget = useBudget(user?.uid, selected?.id);
  const categories = useMaster(selected?.id, 'categories'); const statuses = useMaster(selected?.id, 'paymentStatuses');
  if (!selected) return <Screen><Header title="GharKhata" /><EmptyState icon="⌂" title="Start with your project" body="Create your first construction project to see spending and budget health here." action={<Button onPress={() => router.push('/(app)/project-form')}>Create project</Button>} /></Screen>;
  const canEdit = Boolean(selected.status === 'active' && user && ['admin', 'editor'].includes(selected.role));
  const canPlan = Boolean(selected.status === 'active' && user && selected.role === 'admin');
  const spent = expenseTotal(expenses); const totalBudget = budget?.totalBudget || selected.totalBudget; const overrun = Math.max(spent - totalBudget, 0); const isOverBudget = Boolean(totalBudget && overrun > 0); const remaining = Math.max(totalBudget - spent, 0); const percentage = totalBudget ? Math.min(Math.round((spent / totalBudget) * 100), 100) : 0; const topCategories = categoryTotals(expenses, categories).slice(0, 3);
  return <Screen><Header title="Good day" subtitle={selected.status === 'archived' ? 'Archived project · view only.' : 'Here’s your construction at a glance.'} right={<ProjectPicker projects={projects} />} /><Card style={{ ...styles.hero, ...(isOverBudget ? styles.overrunHero : {}) }}><View style={styles.heroTop}><View><Text style={styles.heroLabel}>{isOverBudget ? 'BUDGET EXCEEDED' : 'TOTAL SPENT'}</Text><Text style={styles.heroAmount}>{isOverBudget ? `${formatCurrency(overrun, currency)} over` : formatCurrency(spent, currency)}</Text></View><Pill tone={isOverBudget ? 'coral' : percentage > 90 ? 'amber' : 'green'}>{totalBudget ? isOverBudget ? 'Over budget' : `${percentage}% of budget` : 'No budget set'}</Pill></View><View style={styles.progressTrack}><View style={[styles.progress, isOverBudget && styles.overrunProgress, { width: `${percentage}%` }]} /></View><View style={styles.heroFoot}><Text style={styles.heroFootText}>{isOverBudget ? 'Total spent' : 'Remaining'}</Text><Text style={styles.heroFootAmount}>{totalBudget ? isOverBudget ? formatCurrency(spent, currency) : formatCurrency(remaining, currency) : 'Set a budget'}</Text></View></Card>{isOverBudget ? <Card style={styles.warning}><Text style={styles.warningTitle}>Your project has exceeded its budget</Text><Text style={styles.warningText}>{formatCurrency(overrun, currency)} is over the budget. Review the plan or upcoming expenses.</Text>{canPlan ? <Button variant="secondary" onPress={() => router.push('/(app)/budget-form')}>Review budget</Button> : null}</Card> : null}<View style={styles.metricRow}><Metric label="This month" value={formatCurrency(monthTotal(expenses), currency)} /><Metric label="Pending" value={formatCurrency(expenses.filter((item) => statuses.find((status) => status.id === item.paymentStatusId)?.name !== 'Paid').reduce((sum, item) => sum + item.amount, 0), currency)} /></View>{canEdit ? <View style={styles.addRow}><View><Text style={styles.addTitle}>Log today’s spend</Text><Text style={styles.addSub}>Takes less than a minute.</Text></View><Button onPress={() => router.push('/(app)/expense-form')}>＋ Add expense</Button></View> : <Text style={styles.viewer}>{selected.status === 'archived' ? 'This archived project is read-only.' : 'You have view-only access to this project.'}</Text>}<SectionTitle title="Where money is going" action={expenses.length ? 'Live' : undefined} />{topCategories.length ? <Card style={styles.breakdown}>{topCategories.map((item) => <View key={item.id} style={styles.breakRow}><View style={styles.breakName}><View style={styles.dot} /><Text style={styles.breakText}>{item.name}</Text></View><Text style={styles.breakAmount}>{formatCurrency(item.amount, currency)}</Text></View>)}</Card> : <EmptyState icon="◌" title="No expenses yet" body="Your spending picture will appear after your first expense." />}</Screen>;
}
function Metric({ label, value }: { label: string; value: string }) { return <Card style={styles.metric}><Text style={styles.metricLabel}>{label.toUpperCase()}</Text><Text numberOfLines={1} style={styles.metricValue}>{value}</Text></Card>; }
const styles = StyleSheet.create({ hero: { backgroundColor: colors.forest, borderColor: colors.forest, gap: 17 }, overrunHero: { backgroundColor: colors.coral, borderColor: colors.coral }, heroTop: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 }, heroLabel: { color: '#FFF6F3', fontWeight: '800', letterSpacing: 1, fontSize: 11 }, heroAmount: { color: 'white', fontWeight: '900', letterSpacing: -.8, fontSize: 31, marginTop: 4 }, progressTrack: { height: 8, backgroundColor: 'rgba(255,255,255,.28)', borderRadius: 8, overflow: 'hidden' }, progress: { height: '100%', backgroundColor: colors.lime, borderRadius: 8 }, overrunProgress: { backgroundColor: '#8B2E1F' }, heroFoot: { flexDirection: 'row', justifyContent: 'space-between' }, heroFootText: { color: '#FFF6F3', fontWeight: '700' }, heroFootAmount: { color: 'white', fontWeight: '800' }, warning: { backgroundColor: '#FFF0EB', borderColor: '#F5B6A8', gap: 8 }, warningTitle: { color: '#8B2E1F', fontWeight: '900', fontSize: 16 }, warningText: { color: colors.ink, fontSize: 13, lineHeight: 19 }, metricRow: { flexDirection: 'row', gap: 12 }, metric: { flex: 1, padding: 15, gap: 6 }, metricLabel: { fontSize: 10, letterSpacing: .7, color: colors.muted, fontWeight: '800' }, metricValue: { color: colors.ink, fontWeight: '900', fontSize: 17 }, addRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 12, alignItems: 'center', paddingVertical: 4 }, addTitle: { color: colors.ink, fontWeight: '900', fontSize: 17 }, addSub: { color: colors.muted, fontSize: 13, marginTop: 3 }, viewer: { color: colors.muted, textAlign: 'center', fontSize: 13 }, breakdown: { gap: 16 }, breakRow: { flexDirection: 'row', justifyContent: 'space-between' }, breakName: { flexDirection: 'row', alignItems: 'center', gap: 9 }, dot: { width: 9, height: 9, borderRadius: 9, backgroundColor: colors.forest }, breakText: { color: colors.ink, fontWeight: '700' }, breakAmount: { color: colors.ink, fontWeight: '900' } });
