import { useState } from 'react';
import { Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import { colors } from '@/constants/design';
import { profileRepository } from '@/repositories/profile-repository';
import type { Project } from '@/types/domain';
import { useApp } from '@/providers/app-provider';

export function ProjectPicker({ projects }: { projects: Project[] }) {
  const { user, profile } = useApp(); const [open, setOpen] = useState(false); const current = projects.find((project) => project.id === profile?.selectedProjectId) ?? projects[0];
  if (!current) return null;
  const archived = current.status === 'archived';
  return <><Pressable onPress={() => setOpen(true)} style={[styles.trigger, archived && styles.archivedTrigger]}><View style={styles.triggerText}><Text numberOfLines={1} style={styles.overline}>{archived ? 'ARCHIVED PROJECT' : 'ACTIVE PROJECT'}</Text><Text numberOfLines={1} style={styles.name}>{current.name}</Text></View><Text style={styles.arrow}>⌄</Text></Pressable><Modal visible={open} transparent animationType="slide"><Pressable style={styles.backdrop} onPress={() => setOpen(false)}><Pressable style={styles.sheet}><Text style={styles.title}>Switch project</Text>{projects.map((project) => <Pressable key={project.id} onPress={async () => { if (user) await profileRepository.selectProject(user.uid, project.id); setOpen(false); }} style={styles.item}><View style={styles.itemText}><Text numberOfLines={1} style={styles.itemName}>{project.name}</Text>{project.status === 'archived' ? <Text style={styles.archivedLabel}>Archived · view only</Text> : null}</View>{project.id === current.id ? <Text style={styles.check}>✓</Text> : null}</Pressable>)}</Pressable></Pressable></Modal></>;
}
const styles = StyleSheet.create({ trigger: { width: 148, maxWidth: '100%', flexShrink: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 7, backgroundColor: colors.mint, paddingHorizontal: 11, paddingVertical: 9, borderRadius: 14 }, triggerText: { flex: 1, minWidth: 0 }, archivedTrigger: { backgroundColor: colors.slate }, overline: { color: colors.forest, fontSize: 9, fontWeight: '900', letterSpacing: .8 }, name: { color: colors.ink, fontSize: 13, fontWeight: '800' }, arrow: { color: colors.forest, fontSize: 18 }, backdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,.35)', justifyContent: 'flex-end' }, sheet: { backgroundColor: 'white', padding: 22, borderTopLeftRadius: 26, borderTopRightRadius: 26 }, title: { color: colors.ink, fontWeight: '900', fontSize: 20, marginBottom: 8 }, item: { paddingVertical: 16, borderBottomColor: '#E7EAE5', borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', gap: 12 }, itemText: { flex: 1, minWidth: 0 }, itemName: { color: colors.ink, fontSize: 16, fontWeight: '700' }, archivedLabel: { color: colors.muted, marginTop: 3, fontSize: 12, fontWeight: '700' }, check: { color: colors.forest, fontSize: 18, fontWeight: '900' } });
