import { router, useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { AuditText, Button, Card, EmptyState, Field, Header, Screen } from '@/components/ui';
import { colors } from '@/constants/design';
import { useMaster, useProjects } from '@/hooks/use-project-data';
import { masterRepository } from '@/repositories/master-repository';
import { useApp } from '@/providers/app-provider';
import type { MasterType } from '@/types/domain';

const labels: Record<MasterType, string> = { categories: 'Categories', stages: 'Stages', vendors: 'Vendors', units: 'Units', paymentMethods: 'Payment methods', paymentStatuses: 'Payment statuses' };
const valid = Object.keys(labels) as MasterType[];

export default function MasterScreen() {
  const { type: raw } = useLocalSearchParams<{ type: MasterType }>(); const type = valid.includes(raw) ? raw : 'categories';
  const { user, profile } = useApp(); const projects = useProjects(user?.uid); const project = projects.find((item) => item.id === profile?.selectedProjectId) ?? projects[0];
  const items = useMaster(project?.id, type); const [name, setName] = useState(''); const [saving, setSaving] = useState(false); const [editingId, setEditingId] = useState<string>(); const [editingName, setEditingName] = useState('');
  const canEdit = Boolean(project && project.status === 'active' && user && (project.ownerId === user.uid || ['admin', 'editor'].includes(project.memberRoles[user.uid])));
  const add = async () => { if (!user || !project || !name.trim()) return; setSaving(true); try { await masterRepository.create(user.uid, project.id, type, name, profile?.displayName || user.displayName || 'Project member'); setName(''); } catch { Alert.alert('Could not add item', 'Please try again.'); } finally { setSaving(false); } };
  const edit = async () => { if (!user || !editingId || !editingName.trim()) return; setSaving(true); try { await masterRepository.update(user.uid, profile?.displayName || user.displayName || 'Project member', type, editingId, editingName); setEditingId(undefined); } catch { Alert.alert('Could not rename item', 'Please try again.'); } finally { setSaving(false); } };
  const remove = async (id: string, value: string) => { if (!project) return; const dependencies = await masterRepository.dependencies(project.id, type, id); if (dependencies) return Alert.alert(`Cannot delete ${value}`, `This item is being used by ${dependencies} expense${dependencies === 1 ? '' : 's'}. Update or delete those expenses first.`); Alert.alert(`Delete ${value}?`, 'This only removes the unused dropdown value.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: () => masterRepository.delete(type, id) }]); };
  if (!project) return <Screen><EmptyState title="Create a project first" body="Dropdown choices are shared within each project." action={<Button onPress={() => router.push('/(app)/project-form')}>Create project</Button>} /></Screen>;
  return <Screen><Header title={labels[type]} subtitle={project.status === 'archived' ? 'Archived project · view only.' : canEdit ? 'Choices shared with your project team.' : 'View-only shared project choices.'} />{canEdit && (editingId ? <Card style={styles.rename}><Field label="Rename item" value={editingName} onChangeText={setEditingName} autoFocus /><View style={styles.renameActions}><Button variant="ghost" style={styles.renameButton} onPress={() => setEditingId(undefined)}>Cancel</Button><Button loading={saving} style={styles.renameButton} onPress={edit}>Save</Button></View></Card> : <View style={styles.add}><Field style={styles.input} label="New item" value={name} onChangeText={setName} placeholder={`Add ${labels[type].toLowerCase().slice(0, -1)}`} onSubmitEditing={add} /><Button loading={saving} style={styles.button} onPress={add}>Add</Button></View>)}{items.length ? <Card style={styles.list}>{items.map((item) => <View key={item.id} style={styles.row}>{canEdit ? <Pressable style={styles.name} onPress={() => { setEditingId(item.id); setEditingName(item.name); }}><Text style={styles.itemName}>{item.name}</Text><Text style={styles.edit}>Tap to rename</Text><AuditText createdByName={item.createdByName} updatedByName={item.updatedByName} /></Pressable> : <View style={styles.name}><Text style={styles.itemName}>{item.name}</Text><AuditText createdByName={item.createdByName} updatedByName={item.updatedByName} /></View>}{canEdit ? <Pressable onPress={() => remove(item.id, item.name)} style={styles.delete}><Text>×</Text></Pressable> : null}</View>)}</Card> : <EmptyState title={`No ${labels[type].toLowerCase()} yet`} body="Add a value to use it in expense entry." />}<Button variant="ghost" onPress={() => router.back()}>Done</Button></Screen>;
}
const styles = StyleSheet.create({ add: { gap: 12 }, input: { width: '100%' }, button: { width: '100%' }, rename: { gap: 12 }, renameActions: { flexDirection: 'row', gap: 8 }, renameButton: { flex: 1 }, list: { paddingVertical: 0 }, row: { minHeight: 62, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomColor: colors.line, borderBottomWidth: 1 }, name: { flex: 1, paddingVertical: 10 }, itemName: { color: colors.ink, fontWeight: '800', fontSize: 16 }, edit: { color: colors.muted, fontSize: 11, marginTop: 3 }, delete: { height: 34, width: 34, borderRadius: 17, backgroundColor: '#FFEAE5', alignItems: 'center', justifyContent: 'center' } });
